//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAQ_Net.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FAQ_Net.Sql.CreateTable", typeof(CreateTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE category (
        ///  id_category INTEGER PRIMARY KEY NOT NULL DEFAULT (null),
        ///  name_category VARCHAR NOT NULL,
        ///  parent_category INTEGER DEFAULT (null),
        ///  count_child INTEGER NOT NULL  DEFAULT 0).
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE otvet (
        ///  id_content INTEGER PRIMARY KEY NOT NULL,
        ///  answer_txt VARCHAR DEFAULT (null),
        ///  answer_rtf VARCHAR DEFAULT (null),
        ///  create_date DATETIME DEFAULT (CURRENT_TIMESTAMP),
        ///  modif_date DATETIME).
        /// </summary>
        internal static string otvet {
            get {
                return ResourceManager.GetString("otvet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE vopros (
        ///  id_content INTEGER PRIMARY KEY NOT NULL,
        ///  id_category INTEGER NOT NULL,
        ///  question VARCHAR NOT NULL,
        ///  create_date DATETIME DEFAULT (CURRENT_TIMESTAMP),
        ///  modif_date DATETIME,
        ///  favorite_date DATETIME).
        /// </summary>
        internal static string vopros {
            get {
                return ResourceManager.GetString("vopros", resourceCulture);
            }
        }
    }
}
